export interface Airport {
  iata: string
  name: string
  city: string
  country: string
}

export const airports: Airport[] = [
  // United States
  { iata: "ATL", name: "Hartsfield-Jackson Atlanta International", city: "Atlanta", country: "US" },
  { iata: "LAX", name: "Los Angeles International", city: "Los Angeles", country: "US" },
  { iata: "ORD", name: "O'Hare International", city: "Chicago", country: "US" },
  { iata: "DFW", name: "Dallas/Fort Worth International", city: "Dallas", country: "US" },
  { iata: "DEN", name: "Denver International", city: "Denver", country: "US" },
  { iata: "JFK", name: "John F. Kennedy International", city: "New York", country: "US" },
  { iata: "SFO", name: "San Francisco International", city: "San Francisco", country: "US" },
  { iata: "SEA", name: "Seattle-Tacoma International", city: "Seattle", country: "US" },
  { iata: "LAS", name: "Harry Reid International", city: "Las Vegas", country: "US" },
  { iata: "MCO", name: "Orlando International", city: "Orlando", country: "US" },
  { iata: "EWR", name: "Newark Liberty International", city: "Newark", country: "US" },
  { iata: "MIA", name: "Miami International", city: "Miami", country: "US" },
  { iata: "CLT", name: "Charlotte Douglas International", city: "Charlotte", country: "US" },
  { iata: "PHX", name: "Phoenix Sky Harbor International", city: "Phoenix", country: "US" },
  { iata: "IAH", name: "George Bush Intercontinental", city: "Houston", country: "US" },
  { iata: "BOS", name: "Logan International", city: "Boston", country: "US" },
  { iata: "MSP", name: "Minneapolis-Saint Paul International", city: "Minneapolis", country: "US" },
  { iata: "DTW", name: "Detroit Metropolitan Wayne County", city: "Detroit", country: "US" },
  { iata: "FLL", name: "Fort Lauderdale-Hollywood International", city: "Fort Lauderdale", country: "US" },
  { iata: "PHL", name: "Philadelphia International", city: "Philadelphia", country: "US" },
  { iata: "LGA", name: "LaGuardia", city: "New York", country: "US" },
  { iata: "BWI", name: "Baltimore/Washington International", city: "Baltimore", country: "US" },
  { iata: "DCA", name: "Ronald Reagan Washington National", city: "Washington", country: "US" },
  { iata: "IAD", name: "Washington Dulles International", city: "Washington", country: "US" },
  { iata: "MDW", name: "Chicago Midway International", city: "Chicago", country: "US" },
  { iata: "TPA", name: "Tampa International", city: "Tampa", country: "US" },
  { iata: "SAN", name: "San Diego International", city: "San Diego", country: "US" },
  { iata: "PDX", name: "Portland International", city: "Portland", country: "US" },
  { iata: "STL", name: "St. Louis Lambert International", city: "St. Louis", country: "US" },
  { iata: "HNL", name: "Daniel K. Inouye International", city: "Honolulu", country: "US" },
  { iata: "BNA", name: "Nashville International", city: "Nashville", country: "US" },
  { iata: "AUS", name: "Austin-Bergstrom International", city: "Austin", country: "US" },
  { iata: "OAK", name: "Oakland International", city: "Oakland", country: "US" },
  { iata: "SJC", name: "Norman Y. Mineta San Jose International", city: "San Jose", country: "US" },
  { iata: "RDU", name: "Raleigh-Durham International", city: "Raleigh", country: "US" },
  { iata: "SMF", name: "Sacramento International", city: "Sacramento", country: "US" },
  { iata: "SLC", name: "Salt Lake City International", city: "Salt Lake City", country: "US" },
  { iata: "SAT", name: "San Antonio International", city: "San Antonio", country: "US" },
  { iata: "IND", name: "Indianapolis International", city: "Indianapolis", country: "US" },
  { iata: "CLE", name: "Cleveland Hopkins International", city: "Cleveland", country: "US" },
  { iata: "MCI", name: "Kansas City International", city: "Kansas City", country: "US" },
  { iata: "CMH", name: "John Glenn Columbus International", city: "Columbus", country: "US" },
  { iata: "PIT", name: "Pittsburgh International", city: "Pittsburgh", country: "US" },
  { iata: "MEM", name: "Memphis International", city: "Memphis", country: "US" },
  { iata: "MSY", name: "Louis Armstrong New Orleans International", city: "New Orleans", country: "US" },
  { iata: "BDL", name: "Bradley International", city: "Hartford", country: "US" },
  { iata: "MKE", name: "General Mitchell International", city: "Milwaukee", country: "US" },
  { iata: "OMA", name: "Eppley Airfield", city: "Omaha", country: "US" },
  { iata: "DSM", name: "Des Moines International", city: "Des Moines", country: "US" },
  { iata: "CID", name: "The Eastern Iowa Airport", city: "Cedar Rapids", country: "US" },
  { iata: "MLI", name: "Quad City International", city: "Moline", country: "US" },
  { iata: "DBQ", name: "Dubuque Regional", city: "Dubuque", country: "US" },
  { iata: "FOD", name: "Fort Dodge Regional", city: "Fort Dodge", country: "US" },
  { iata: "ALO", name: "Waterloo Regional", city: "Waterloo", country: "US" },
  { iata: "SBN", name: "South Bend International", city: "South Bend", country: "US" },
  { iata: "GRR", name: "Gerald R. Ford International", city: "Grand Rapids", country: "US" },
  { iata: "ABQ", name: "Albuquerque International Sunport", city: "Albuquerque", country: "US" },
  { iata: "TUL", name: "Tulsa International", city: "Tulsa", country: "US" },
  { iata: "OKC", name: "Will Rogers World Airport", city: "Oklahoma City", country: "US" },
  { iata: "ELP", name: "El Paso International", city: "El Paso", country: "US" },
  { iata: "BUF", name: "Buffalo Niagara International", city: "Buffalo", country: "US" },
  { iata: "ALB", name: "Albany International", city: "Albany", country: "US" },
  { iata: "ROC", name: "Greater Rochester International", city: "Rochester", country: "US" },
  { iata: "SYR", name: "Syracuse Hancock International", city: "Syracuse", country: "US" },
  { iata: "RIC", name: "Richmond International", city: "Richmond", country: "US" },
  { iata: "ORF", name: "Norfolk International", city: "Norfolk", country: "US" },
  { iata: "GSO", name: "Piedmont Triad International", city: "Greensboro", country: "US" },
  { iata: "CHS", name: "Charleston International", city: "Charleston", country: "US" },
  { iata: "SAV", name: "Savannah/Hilton Head International", city: "Savannah", country: "US" },
  { iata: "JAX", name: "Jacksonville International", city: "Jacksonville", country: "US" },
  { iata: "RSW", name: "Southwest Florida International", city: "Fort Myers", country: "US" },
  { iata: "PBI", name: "Palm Beach International", city: "West Palm Beach", country: "US" },
  { iata: "SRQ", name: "Sarasota Bradenton International", city: "Sarasota", country: "US" },
  { iata: "GNV", name: "Gainesville Regional", city: "Gainesville", country: "US" },
  { iata: "TLH", name: "Tallahassee International", city: "Tallahassee", country: "US" },
  { iata: "PWM", name: "Portland International Jetport", city: "Portland", country: "US" },
  { iata: "BTV", name: "Burlington International", city: "Burlington", country: "US" },
  { iata: "MHT", name: "Manchester-Boston Regional", city: "Manchester", country: "US" },
  { iata: "PVD", name: "T.F. Green International", city: "Providence", country: "US" },
  { iata: "BGR", name: "Bangor International", city: "Bangor", country: "US" },
  { iata: "SDF", name: "Louisville Muhammad Ali International", city: "Louisville", country: "US" },
  { iata: "CVG", name: "Cincinnati/Northern Kentucky International", city: "Cincinnati", country: "US" },
  { iata: "DAY", name: "Dayton International", city: "Dayton", country: "US" },
  { iata: "LEX", name: "Blue Grass Airport", city: "Lexington", country: "US" },
  { iata: "HSV", name: "Huntsville International", city: "Huntsville", country: "US" },
  { iata: "BHM", name: "Birmingham-Shuttlesworth International", city: "Birmingham", country: "US" },
  { iata: "MOB", name: "Mobile Regional", city: "Mobile", country: "US" },
  { iata: "JAN", name: "Jackson-Medgar Wiley Evers International", city: "Jackson", country: "US" },
  { iata: "LIT", name: "Bill and Hillary Clinton National", city: "Little Rock", country: "US" },
  { iata: "SHV", name: "Shreveport Regional", city: "Shreveport", country: "US" },
  { iata: "BTR", name: "Baton Rouge Metropolitan", city: "Baton Rouge", country: "US" },
  { iata: "GPT", name: "Gulfport-Biloxi International", city: "Gulfport", country: "US" },
  { iata: "ICT", name: "Wichita Dwight D. Eisenhower National", city: "Wichita", country: "US" },
  { iata: "COS", name: "Colorado Springs Airport", city: "Colorado Springs", country: "US" },
  { iata: "GJT", name: "Grand Junction Regional", city: "Grand Junction", country: "US" },
  { iata: "BOI", name: "Boise Airport", city: "Boise", country: "US" },
  { iata: "RNO", name: "Reno-Tahoe International", city: "Reno", country: "US" },
  { iata: "LAS", name: "Harry Reid International", city: "Las Vegas", country: "US" },
  { iata: "TUS", name: "Tucson International", city: "Tucson", country: "US" },
  { iata: "GEG", name: "Spokane International", city: "Spokane", country: "US" },
  { iata: "MFR", name: "Rogue Valley International-Medford", city: "Medford", country: "US" },
  { iata: "EUG", name: "Eugene Airport", city: "Eugene", country: "US" },
  { iata: "BLI", name: "Bellingham International", city: "Bellingham", country: "US" },
  { iata: "FAI", name: "Fairbanks International", city: "Fairbanks", country: "US" },
  { iata: "ANC", name: "Ted Stevens Anchorage International", city: "Anchorage", country: "US" },
  { iata: "JNU", name: "Juneau International", city: "Juneau", country: "US" },
  { iata: "KOA", name: "Ellison Onizuka Kona International", city: "Kailua-Kona", country: "US" },
  { iata: "OGG", name: "Kahului Airport", city: "Maui", country: "US" },
  { iata: "LIH", name: "Lihue Airport", city: "Lihue", country: "US" },
  { iata: "ITO", name: "Hilo International", city: "Hilo", country: "US" },
  { iata: "MYR", name: "Myrtle Beach International", city: "Myrtle Beach", country: "US" },
  { iata: "FAY", name: "Fayetteville Regional", city: "Fayetteville", country: "US" },
  { iata: "AVL", name: "Asheville Regional", city: "Asheville", country: "US" },
  { iata: "GSP", name: "Greenville-Spartanburg International", city: "Greenville", country: "US" },
  { iata: "CAE", name: "Columbia Metropolitan", city: "Columbia", country: "US" },
  // Canada
  { iata: "YYZ", name: "Toronto Pearson International", city: "Toronto", country: "CA" },
  { iata: "YVR", name: "Vancouver International", city: "Vancouver", country: "CA" },
  { iata: "YUL", name: "Montréal-Trudeau International", city: "Montreal", country: "CA" },
  { iata: "YYC", name: "Calgary International", city: "Calgary", country: "CA" },
  { iata: "YEG", name: "Edmonton International", city: "Edmonton", country: "CA" },
  { iata: "YOW", name: "Ottawa Macdonald-Cartier International", city: "Ottawa", country: "CA" },
  { iata: "YHZ", name: "Halifax Stanfield International", city: "Halifax", country: "CA" },
  { iata: "YWG", name: "James Armstrong Richardson International", city: "Winnipeg", country: "CA" },
  { iata: "YQR", name: "Regina International", city: "Regina", country: "CA" },
  { iata: "YXE", name: "Saskatoon John G. Diefenbaker International", city: "Saskatoon", country: "CA" },
  // United Kingdom
  { iata: "LHR", name: "Heathrow", city: "London", country: "GB" },
  { iata: "LGW", name: "Gatwick", city: "London", country: "GB" },
  { iata: "MAN", name: "Manchester Airport", city: "Manchester", country: "GB" },
  { iata: "STN", name: "Stansted", city: "London", country: "GB" },
  { iata: "LTN", name: "Luton", city: "London", country: "GB" },
  { iata: "LCY", name: "London City", city: "London", country: "GB" },
  { iata: "EDI", name: "Edinburgh Airport", city: "Edinburgh", country: "GB" },
  { iata: "BHX", name: "Birmingham Airport", city: "Birmingham", country: "GB" },
  { iata: "GLA", name: "Glasgow Airport", city: "Glasgow", country: "GB" },
  { iata: "BRS", name: "Bristol Airport", city: "Bristol", country: "GB" },
  { iata: "NCL", name: "Newcastle Airport", city: "Newcastle", country: "GB" },
  // Europe
  { iata: "CDG", name: "Charles de Gaulle", city: "Paris", country: "FR" },
  { iata: "ORY", name: "Orly", city: "Paris", country: "FR" },
  { iata: "NCE", name: "Nice Côte d'Azur", city: "Nice", country: "FR" },
  { iata: "LYS", name: "Lyon-Saint Exupéry", city: "Lyon", country: "FR" },
  { iata: "MRS", name: "Marseille Provence", city: "Marseille", country: "FR" },
  { iata: "FRA", name: "Frankfurt am Main", city: "Frankfurt", country: "DE" },
  { iata: "MUC", name: "Munich Airport", city: "Munich", country: "DE" },
  { iata: "TXL", name: "Berlin Tegel", city: "Berlin", country: "DE" },
  { iata: "BER", name: "Berlin Brandenburg", city: "Berlin", country: "DE" },
  { iata: "DUS", name: "Düsseldorf Airport", city: "Düsseldorf", country: "DE" },
  { iata: "HAM", name: "Hamburg Airport", city: "Hamburg", country: "DE" },
  { iata: "CGN", name: "Cologne Bonn Airport", city: "Cologne", country: "DE" },
  { iata: "STR", name: "Stuttgart Airport", city: "Stuttgart", country: "DE" },
  { iata: "AMS", name: "Amsterdam Airport Schiphol", city: "Amsterdam", country: "NL" },
  { iata: "EIN", name: "Eindhoven Airport", city: "Eindhoven", country: "NL" },
  { iata: "MAD", name: "Adolfo Suárez Madrid-Barajas", city: "Madrid", country: "ES" },
  { iata: "BCN", name: "Barcelona-El Prat", city: "Barcelona", country: "ES" },
  { iata: "AGP", name: "Málaga-Costa del Sol", city: "Malaga", country: "ES" },
  { iata: "PMI", name: "Palma de Mallorca", city: "Palma", country: "ES" },
  { iata: "VLC", name: "Valencia Airport", city: "Valencia", country: "ES" },
  { iata: "SVQ", name: "Seville Airport", city: "Seville", country: "ES" },
  { iata: "FCO", name: "Leonardo da Vinci–Fiumicino", city: "Rome", country: "IT" },
  { iata: "CIA", name: "Ciampino Airport", city: "Rome", country: "IT" },
  { iata: "MXP", name: "Milan Malpensa", city: "Milan", country: "IT" },
  { iata: "LIN", name: "Milan Linate", city: "Milan", country: "IT" },
  { iata: "BGY", name: "Milan Bergamo", city: "Milan", country: "IT" },
  { iata: "VCE", name: "Venice Marco Polo", city: "Venice", country: "IT" },
  { iata: "NAP", name: "Naples International", city: "Naples", country: "IT" },
  { iata: "PMO", name: "Palermo Airport", city: "Palermo", country: "IT" },
  { iata: "CTA", name: "Catania-Fontanarossa", city: "Catania", country: "IT" },
  { iata: "BRU", name: "Brussels Airport", city: "Brussels", country: "BE" },
  { iata: "CRL", name: "Brussels South Charleroi", city: "Brussels", country: "BE" },
  { iata: "ZUR", name: "Zurich Airport", city: "Zurich", country: "CH" },
  { iata: "ZRH", name: "Zurich Airport", city: "Zurich", country: "CH" },
  { iata: "GVA", name: "Geneva Airport", city: "Geneva", country: "CH" },
  { iata: "VIE", name: "Vienna International", city: "Vienna", country: "AT" },
  { iata: "CPH", name: "Copenhagen Airport", city: "Copenhagen", country: "DK" },
  { iata: "ARN", name: "Stockholm Arlanda", city: "Stockholm", country: "SE" },
  { iata: "NYO", name: "Stockholm Skavsta", city: "Stockholm", country: "SE" },
  { iata: "OSL", name: "Oslo Airport Gardermoen", city: "Oslo", country: "NO" },
  { iata: "HEL", name: "Helsinki-Vantaa", city: "Helsinki", country: "FI" },
  { iata: "LIS", name: "Humberto Delgado Airport", city: "Lisbon", country: "PT" },
  { iata: "OPO", name: "Francisco de Sá Carneiro Airport", city: "Porto", country: "PT" },
  { iata: "FAO", name: "Faro Airport", city: "Faro", country: "PT" },
  { iata: "ATH", name: "Athens International", city: "Athens", country: "GR" },
  { iata: "SKG", name: "Thessaloniki Macedonia", city: "Thessaloniki", country: "GR" },
  { iata: "HER", name: "Heraklion International", city: "Heraklion", country: "GR" },
  { iata: "WAW", name: "Warsaw Chopin Airport", city: "Warsaw", country: "PL" },
  { iata: "KRK", name: "Kraków John Paul II International", city: "Krakow", country: "PL" },
  { iata: "PRG", name: "Václav Havel Airport Prague", city: "Prague", country: "CZ" },
  { iata: "BUD", name: "Budapest Ferenc Liszt International", city: "Budapest", country: "HU" },
  { iata: "OTP", name: "Henri Coandă International", city: "Bucharest", country: "RO" },
  { iata: "SOF", name: "Sofia Airport", city: "Sofia", country: "BG" },
  { iata: "DBV", name: "Dubrovnik Airport", city: "Dubrovnik", country: "HR" },
  { iata: "ZAG", name: "Zagreb Airport", city: "Zagreb", country: "HR" },
  { iata: "BEG", name: "Belgrade Nikola Tesla", city: "Belgrade", country: "RS" },
  { iata: "LJU", name: "Ljubljana Jože Pučnik Airport", city: "Ljubljana", country: "SI" },
  { iata: "RVN", name: "Rovaniemi Airport", city: "Rovaniemi", country: "FI" },
  { iata: "REK", name: "Reykjavik Airport", city: "Reykjavik", country: "IS" },
  { iata: "KEF", name: "Keflavik International", city: "Reykjavik", country: "IS" },
  { iata: "DUB", name: "Dublin Airport", city: "Dublin", country: "IE" },
  { iata: "ORK", name: "Cork Airport", city: "Cork", country: "IE" },
  // Russia / Eastern Europe
  { iata: "SVO", name: "Sheremetyevo International", city: "Moscow", country: "RU" },
  { iata: "DME", name: "Domodedovo International", city: "Moscow", country: "RU" },
  { iata: "LED", name: "Pulkovo Airport", city: "St. Petersburg", country: "RU" },
  // Middle East
  { iata: "DXB", name: "Dubai International", city: "Dubai", country: "AE" },
  { iata: "AUH", name: "Abu Dhabi International", city: "Abu Dhabi", country: "AE" },
  { iata: "DOH", name: "Hamad International", city: "Doha", country: "QA" },
  { iata: "KWI", name: "Kuwait International", city: "Kuwait City", country: "KW" },
  { iata: "BAH", name: "Bahrain International", city: "Manama", country: "BH" },
  { iata: "MCT", name: "Muscat International", city: "Muscat", country: "OM" },
  { iata: "AMM", name: "Queen Alia International", city: "Amman", country: "JO" },
  { iata: "BEY", name: "Rafic Hariri International", city: "Beirut", country: "LB" },
  { iata: "TLV", name: "Ben Gurion International", city: "Tel Aviv", country: "IL" },
  { iata: "CAI", name: "Cairo International", city: "Cairo", country: "EG" },
  { iata: "RUH", name: "King Khalid International", city: "Riyadh", country: "SA" },
  { iata: "JED", name: "King Abdulaziz International", city: "Jeddah", country: "SA" },
  // Africa
  { iata: "JNB", name: "O.R. Tambo International", city: "Johannesburg", country: "ZA" },
  { iata: "CPT", name: "Cape Town International", city: "Cape Town", country: "ZA" },
  { iata: "DUR", name: "King Shaka International", city: "Durban", country: "ZA" },
  { iata: "NBO", name: "Jomo Kenyatta International", city: "Nairobi", country: "KE" },
  { iata: "ADD", name: "Addis Ababa Bole International", city: "Addis Ababa", country: "ET" },
  { iata: "LOS", name: "Murtala Muhammed International", city: "Lagos", country: "NG" },
  { iata: "ABV", name: "Nnamdi Azikiwe International", city: "Abuja", country: "NG" },
  { iata: "ACC", name: "Kotoka International", city: "Accra", country: "GH" },
  { iata: "CMN", name: "Mohammed V International", city: "Casablanca", country: "MA" },
  { iata: "RAK", name: "Marrakesh Menara", city: "Marrakesh", country: "MA" },
  { iata: "ALG", name: "Houari Boumediene Airport", city: "Algiers", country: "DZ" },
  { iata: "TUN", name: "Tunis-Carthage International", city: "Tunis", country: "TN" },
  { iata: "DAR", name: "Julius Nyerere International", city: "Dar es Salaam", country: "TZ" },
  { iata: "LUN", name: "Kenneth Kaunda International", city: "Lusaka", country: "ZM" },
  { iata: "HRE", name: "Robert Gabriel Mugabe International", city: "Harare", country: "ZW" },
  // Asia
  { iata: "PEK", name: "Beijing Capital International", city: "Beijing", country: "CN" },
  { iata: "PKX", name: "Beijing Daxing International", city: "Beijing", country: "CN" },
  { iata: "PVG", name: "Shanghai Pudong International", city: "Shanghai", country: "CN" },
  { iata: "SHA", name: "Shanghai Hongqiao International", city: "Shanghai", country: "CN" },
  { iata: "CAN", name: "Guangzhou Baiyun International", city: "Guangzhou", country: "CN" },
  { iata: "SZX", name: "Shenzhen Bao'an International", city: "Shenzhen", country: "CN" },
  { iata: "CTU", name: "Chengdu Tianfu International", city: "Chengdu", country: "CN" },
  { iata: "XIY", name: "Xi'an Xianyang International", city: "Xi'an", country: "CN" },
  { iata: "WUH", name: "Wuhan Tianhe International", city: "Wuhan", country: "CN" },
  { iata: "CKG", name: "Chongqing Jiangbei International", city: "Chongqing", country: "CN" },
  { iata: "HRB", name: "Harbin Taiping International", city: "Harbin", country: "CN" },
  { iata: "SYX", name: "Sanya Phoenix International", city: "Sanya", country: "CN" },
  { iata: "HGH", name: "Hangzhou Xiaoshan International", city: "Hangzhou", country: "CN" },
  { iata: "NKG", name: "Nanjing Lukou International", city: "Nanjing", country: "CN" },
  { iata: "KMG", name: "Kunming Changshui International", city: "Kunming", country: "CN" },
  { iata: "XMN", name: "Xiamen Gaoqi International", city: "Xiamen", country: "CN" },
  { iata: "HKG", name: "Hong Kong International", city: "Hong Kong", country: "HK" },
  { iata: "MFM", name: "Macau International", city: "Macau", country: "MO" },
  { iata: "TPE", name: "Taiwan Taoyuan International", city: "Taipei", country: "TW" },
  { iata: "TSA", name: "Taipei Songshan", city: "Taipei", country: "TW" },
  { iata: "NRT", name: "Narita International", city: "Tokyo", country: "JP" },
  { iata: "HND", name: "Haneda Airport", city: "Tokyo", country: "JP" },
  { iata: "KIX", name: "Kansai International", city: "Osaka", country: "JP" },
  { iata: "ITM", name: "Osaka Itami Airport", city: "Osaka", country: "JP" },
  { iata: "CTS", name: "New Chitose Airport", city: "Sapporo", country: "JP" },
  { iata: "FUK", name: "Fukuoka Airport", city: "Fukuoka", country: "JP" },
  { iata: "OKA", name: "Naha Airport", city: "Naha", country: "JP" },
  { iata: "NGO", name: "Chubu Centrair International", city: "Nagoya", country: "JP" },
  { iata: "ICN", name: "Incheon International", city: "Seoul", country: "KR" },
  { iata: "GMP", name: "Gimpo International", city: "Seoul", country: "KR" },
  { iata: "CJU", name: "Jeju International", city: "Jeju", country: "KR" },
  { iata: "PUS", name: "Gimhae International", city: "Busan", country: "KR" },
  { iata: "BKK", name: "Suvarnabhumi Airport", city: "Bangkok", country: "TH" },
  { iata: "DMK", name: "Don Mueang International", city: "Bangkok", country: "TH" },
  { iata: "CNX", name: "Chiang Mai International", city: "Chiang Mai", country: "TH" },
  { iata: "HKT", name: "Phuket International", city: "Phuket", country: "TH" },
  { iata: "USM", name: "Samui Airport", city: "Koh Samui", country: "TH" },
  { iata: "SIN", name: "Singapore Changi", city: "Singapore", country: "SG" },
  { iata: "KUL", name: "Kuala Lumpur International", city: "Kuala Lumpur", country: "MY" },
  { iata: "SZB", name: "Sultan Abdul Aziz Shah Airport", city: "Kuala Lumpur", country: "MY" },
  { iata: "CGK", name: "Soekarno-Hatta International", city: "Jakarta", country: "ID" },
  { iata: "DPS", name: "Ngurah Rai International", city: "Bali", country: "ID" },
  { iata: "SUB", name: "Juanda International", city: "Surabaya", country: "ID" },
  { iata: "MNL", name: "Ninoy Aquino International", city: "Manila", country: "PH" },
  { iata: "CEB", name: "Mactan-Cebu International", city: "Cebu", country: "PH" },
  { iata: "SGN", name: "Tan Son Nhat International", city: "Ho Chi Minh City", country: "VN" },
  { iata: "HAN", name: "Noi Bai International", city: "Hanoi", country: "VN" },
  { iata: "DAD", name: "Da Nang International", city: "Da Nang", country: "VN" },
  { iata: "REP", name: "Siem Reap International", city: "Siem Reap", country: "KH" },
  { iata: "PNH", name: "Phnom Penh International", city: "Phnom Penh", country: "KH" },
  { iata: "RGN", name: "Yangon International", city: "Yangon", country: "MM" },
  { iata: "DEL", name: "Indira Gandhi International", city: "Delhi", country: "IN" },
  { iata: "BOM", name: "Chhatrapati Shivaji Maharaj International", city: "Mumbai", country: "IN" },
  { iata: "MAA", name: "Chennai International", city: "Chennai", country: "IN" },
  { iata: "BLR", name: "Kempegowda International", city: "Bangalore", country: "IN" },
  { iata: "HYD", name: "Rajiv Gandhi International", city: "Hyderabad", country: "IN" },
  { iata: "CCU", name: "Netaji Subhas Chandra Bose International", city: "Kolkata", country: "IN" },
  { iata: "COK", name: "Cochin International", city: "Kochi", country: "IN" },
  { iata: "AMD", name: "Sardar Vallabhbhai Patel International", city: "Ahmedabad", country: "IN" },
  { iata: "GOI", name: "Goa International", city: "Goa", country: "IN" },
  { iata: "TRV", name: "Trivandrum International", city: "Thiruvananthapuram", country: "IN" },
  { iata: "KTM", name: "Tribhuvan International", city: "Kathmandu", country: "NP" },
  { iata: "CMB", name: "Bandaranaike International", city: "Colombo", country: "LK" },
  { iata: "DAC", name: "Hazrat Shahjalal International", city: "Dhaka", country: "BD" },
  { iata: "KHI", name: "Jinnah International", city: "Karachi", country: "PK" },
  { iata: "LHE", name: "Allama Iqbal International", city: "Lahore", country: "PK" },
  { iata: "ISB", name: "Islamabad International", city: "Islamabad", country: "PK" },
  { iata: "KBL", name: "Hamid Karzai International", city: "Kabul", country: "AF" },
  // Central Asia / Caucasus
  { iata: "ALA", name: "Almaty International", city: "Almaty", country: "KZ" },
  { iata: "TAS", name: "Islam Karimov Tashkent International", city: "Tashkent", country: "UZ" },
  { iata: "GYD", name: "Heydar Aliyev International", city: "Baku", country: "AZ" },
  { iata: "TBS", name: "Tbilisi International", city: "Tbilisi", country: "GE" },
  { iata: "EVN", name: "Zvartnots International", city: "Yerevan", country: "AM" },
  // Turkey
  { iata: "IST", name: "Istanbul Airport", city: "Istanbul", country: "TR" },
  { iata: "SAW", name: "Sabiha Gökçen International", city: "Istanbul", country: "TR" },
  { iata: "AYT", name: "Antalya Airport", city: "Antalya", country: "TR" },
  { iata: "ESB", name: "Esenboğa International", city: "Ankara", country: "TR" },
  { iata: "ADB", name: "Adnan Menderes Airport", city: "Izmir", country: "TR" },
  // Australia / New Zealand / Pacific
  { iata: "SYD", name: "Kingsford Smith International", city: "Sydney", country: "AU" },
  { iata: "MEL", name: "Melbourne Airport", city: "Melbourne", country: "AU" },
  { iata: "BNE", name: "Brisbane Airport", city: "Brisbane", country: "AU" },
  { iata: "PER", name: "Perth Airport", city: "Perth", country: "AU" },
  { iata: "ADL", name: "Adelaide Airport", city: "Adelaide", country: "AU" },
  { iata: "CBR", name: "Canberra Airport", city: "Canberra", country: "AU" },
  { iata: "DRW", name: "Darwin International", city: "Darwin", country: "AU" },
  { iata: "HBA", name: "Hobart Airport", city: "Hobart", country: "AU" },
  { iata: "OOL", name: "Gold Coast Airport", city: "Gold Coast", country: "AU" },
  { iata: "CNS", name: "Cairns Airport", city: "Cairns", country: "AU" },
  { iata: "AKL", name: "Auckland Airport", city: "Auckland", country: "NZ" },
  { iata: "WLG", name: "Wellington Airport", city: "Wellington", country: "NZ" },
  { iata: "CHC", name: "Christchurch Airport", city: "Christchurch", country: "NZ" },
  { iata: "NAN", name: "Nadi International", city: "Nadi", country: "FJ" },
  { iata: "PPT", name: "Faa'a International", city: "Papeete", country: "PF" },
  { iata: "HNL", name: "Daniel K. Inouye International", city: "Honolulu", country: "US" },
  { iata: "GUM", name: "Antonio B. Won Pat International", city: "Guam", country: "GU" },
  // Mexico / Caribbean / Central America
  { iata: "MEX", name: "Benito Juárez International", city: "Mexico City", country: "MX" },
  { iata: "CUN", name: "Cancún International", city: "Cancun", country: "MX" },
  { iata: "GDL", name: "Don Miguel Hidalgo y Costilla International", city: "Guadalajara", country: "MX" },
  { iata: "MTY", name: "General Mariano Escobedo International", city: "Monterrey", country: "MX" },
  { iata: "TIJ", name: "General Abelardo L. Rodríguez International", city: "Tijuana", country: "MX" },
  { iata: "SJD", name: "Los Cabos International", city: "Los Cabos", country: "MX" },
  { iata: "PVR", name: "Licenciado Gustavo Díaz Ordaz International", city: "Puerto Vallarta", country: "MX" },
  { iata: "MZT", name: "General Rafael Buelna International", city: "Mazatlan", country: "MX" },
  { iata: "MID", name: "Manuel Crescencio Rejón International", city: "Merida", country: "MX" },
  { iata: "HAV", name: "José Martí International", city: "Havana", country: "CU" },
  { iata: "NAS", name: "Lynden Pindling International", city: "Nassau", country: "BS" },
  { iata: "MBJ", name: "Sangster International", city: "Montego Bay", country: "JM" },
  { iata: "KIN", name: "Norman Manley International", city: "Kingston", country: "JM" },
  { iata: "PUJ", name: "Punta Cana International", city: "Punta Cana", country: "DO" },
  { iata: "SDQ", name: "Las Américas International", city: "Santo Domingo", country: "DO" },
  { iata: "SJU", name: "Luis Muñoz Marín International", city: "San Juan", country: "PR" },
  { iata: "ANU", name: "V.C. Bird International", city: "Antigua", country: "AG" },
  { iata: "BGI", name: "Grantley Adams International", city: "Bridgetown", country: "BB" },
  { iata: "UVF", name: "Hewanorra International", city: "St. Lucia", country: "LC" },
  { iata: "STT", name: "Cyril E. King Airport", city: "St. Thomas", country: "VI" },
  { iata: "GCM", name: "Owen Roberts International", city: "Grand Cayman", country: "KY" },
  { iata: "PTY", name: "Tocumen International", city: "Panama City", country: "PA" },
  { iata: "SJO", name: "Juan Santamaría International", city: "San Jose", country: "CR" },
  { iata: "GUA", name: "La Aurora International", city: "Guatemala City", country: "GT" },
  { iata: "SAP", name: "Ramón Villeda Morales International", city: "San Pedro Sula", country: "HN" },
  // South America
  { iata: "GRU", name: "São Paulo-Guarulhos International", city: "São Paulo", country: "BR" },
  { iata: "CGH", name: "São Paulo Congonhas", city: "São Paulo", country: "BR" },
  { iata: "GIG", name: "Rio de Janeiro-Galeão International", city: "Rio de Janeiro", country: "BR" },
  { iata: "SDU", name: "Santos Dumont Airport", city: "Rio de Janeiro", country: "BR" },
  { iata: "BSB", name: "Brasília International", city: "Brasilia", country: "BR" },
  { iata: "SSA", name: "Deputado Luís Eduardo Magalhães International", city: "Salvador", country: "BR" },
  { iata: "FOR", name: "Pinto Martins International", city: "Fortaleza", country: "BR" },
  { iata: "REC", name: "Recife-Guararapes International", city: "Recife", country: "BR" },
  { iata: "POA", name: "Salgado Filho International", city: "Porto Alegre", country: "BR" },
  { iata: "CWB", name: "Afonso Pena International", city: "Curitiba", country: "BR" },
  { iata: "EZE", name: "Ministro Pistarini International", city: "Buenos Aires", country: "AR" },
  { iata: "AEP", name: "Jorge Newbery Airpark", city: "Buenos Aires", country: "AR" },
  { iata: "COR", name: "Ingeniero Ambrosio L.V. Taravella International", city: "Córdoba", country: "AR" },
  { iata: "MDZ", name: "Governor Francisco Gabrielli International", city: "Mendoza", country: "AR" },
  { iata: "SCL", name: "Arturo Merino Benítez International", city: "Santiago", country: "CL" },
  { iata: "LIM", name: "Jorge Chávez International", city: "Lima", country: "PE" },
  { iata: "BOG", name: "El Dorado International", city: "Bogota", country: "CO" },
  { iata: "MDE", name: "José María Córdova International", city: "Medellín", country: "CO" },
  { iata: "CTG", name: "Rafael Núñez International", city: "Cartagena", country: "CO" },
  { iata: "UIO", name: "Mariscal Sucre International", city: "Quito", country: "EC" },
  { iata: "GYE", name: "José Joaquín de Olmedo International", city: "Guayaquil", country: "EC" },
  { iata: "CCS", name: "Simón Bolívar International", city: "Caracas", country: "VE" },
  { iata: "ASU", name: "Silvio Pettirossi International", city: "Asunción", country: "PY" },
  { iata: "MVD", name: "Carrasco International", city: "Montevideo", country: "UY" },
  { iata: "VVI", name: "Viru Viru International", city: "Santa Cruz", country: "BO" },
  { iata: "LPB", name: "El Alto International", city: "La Paz", country: "BO" },
]

export function searchAirports(query: string, limit = 8): Airport[] {
  if (!query || query.length < 2) return []
  const q = query.toLowerCase()
  return airports
    .filter(
      (a) =>
        a.iata.toLowerCase().includes(q) ||
        a.name.toLowerCase().includes(q) ||
        a.city.toLowerCase().includes(q) ||
        a.country.toLowerCase().includes(q)
    )
    .slice(0, limit)
}
